### PR TITLE
Add useful tool textures (and fix toolsinvisibleladder)

### PR DESCRIPTION
**Pull request by SirYodaJedi**
* ~~`tools_viscluster`: (from BMS) same as toolstrigger, but intended for visclusters~~
* `toolsinvisible_nonsolid`: like toolsinvisible, but works on brushes with %compilenonsolid mats
* ~~`toolsinvisibledisplacement`: (from TF2) for displacement clip brushes, since nodraw doesn't work there~~
* `toolsinvisibleladder` - fixed version that doesn't cut visleaves (and has translucency in editor)
* `toolsnodraw_nonsolid`: like toolsnodraw, but works on brushes with %compilenonsolid mats
* ~~`toolstrigger_soundscape`: (from BMS) same as toolstrigger, but intended for soundscape triggers~~

~~If you'd prefer to not take the VTFs from BMS+TF2, just suggest a free font and I can recreate them from scratch.~~ The BMS+TF2 tool textures have been removed.

### CODE REVIEW

**Comment by SirYodaJedi** [comment]
If you'd prefer to not take the VTFs from BMS+TF2, just suggest a free font and I can recreate them from scratch.

**Comment by BreakinBenny** [comment]
This could come in handy. By the way, some of these are in TF2 Classic as well:
- toolsinvisibledisplacement
- the updated toolsinvisibleladder
- toolsviscluster

If you like, you can rename the current VMT and VTF for the last one...

**Comment by BreakinBenny** [comment]
I spoke to YoYo, he's uncertain if we'll have trouble with Crowbar Collective and Valve. He also expressed there could be a risk of having to modify the source code accordingly.

We could probably utilize the VMT modifications to base Source tool textures though.

**Comment by SirYodaJedi** [comment]
Okay, I removed the three from TF2 and BMS and left just the three that I modified from stock HL2 VMTs. Doing a "squash and merge" should prevent them from ending up in the base repo's commit history.

**Pull request merged**
